### ISSUE TITLE
Problems with date parsing and blocking input on SIGTERM

### ISSUE THREAD

**Issue by tolecnal** [ppf2/logstash-input-zendesk#1]
Hello,

I have two issues, that I've tried to fix myself, how with little to no knowledge on Ruby and with how the logstash input plugins work, I've come to a dead stop.

**Problem 1**
It seems like the plugin is unable to parse the 'updated_at' and 'created_at' fields from the API. I've tried changing the format used in the index templates, making my new adjustment this:

`format: yyyy-MM-dd HH:mm:ss z||dateOptionalTime||yyyy-MM-dd HH:mm:ss Z||yyyy-MM-ddTHH:mm:ssZ||yyyy-MM-ddTHH:mm:SS+HH:mm,`

Whereas the standard is:

`format: yyyy-MM-dd HH:mm:ss z||dateOptionalTime||yyyy-MM-dd HH:mm:ss Z`

The first one I added is because this is the format used in the API documentation over at ZenDesk.com and the latter because it's the format I see when I grep the logstash log files.

`
pcregrep --buffer-size=1000000 -o '("created_at"=>".*?")' logstash.log
`
Output
`
"created_at"=>"2016-04-14T18:36:31+02:00"
`

Even with the adjusted 'format', I still can't get it to work.

When I add a new index template to Kibana, this is the error message I get:

> Mapping conflict! 2 fields are defined as several types (string, integer, etc) across the indices that match this pattern. You may still be able to use these conflict fields in parts of Kibana, but they will be unavailable for functions that require Kibana to know their type. Correcting this issue will require reindexing your data.

**Problem 2**

When doing _sudo service logstash stop_ it seems like plugin isn't set up to handle SIGTERM, as the input plugin seems to continue to work and blocks service stop.

```
sudo service logstash stop
Killing logstash (pid 29517) with SIGTERM
Waiting logstash (pid 29517) to die...
Waiting logstash (pid 29517) to die...
Waiting logstash (pid 29517) to die...
Waiting logstash (pid 29517) to die...
Waiting logstash (pid 29517) to die...
Waiting logstash (pid 29517) to die...
Waiting logstash (pid 29517) to die...
Waiting logstash (pid 29517) to die...
Waiting logstash (pid 29517) to die...
logstash stop failed; still running.
```

Is this something you are aware of?

Any help on either of these issues would be greatly appreciated.

**Comment by ppf2** [comment]
The plugin itself doesn't actually do any special parsing of the created_at/updated_at fields. It simply picks up whatever it receives from the API and use that value in the Logstash event field.  So it is important to have the index template set with the appropriate date format *before* indexing any data to Elasticsearch, otherwise, Elasticsearch will create those fields as string fields.  

The default date format in the provided example templates should work with the `2016-04-14T18:36:31+02:00` formatted dates.  Here is an isolated test:

```
DELETE datetest
PUT /datetest
{
  "mappings": {
    "type":{
      "properties": {
        "created_at":{
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss z||dateOptionalTime||yyyy-MM-dd HH:mm:ss Z"
        }
      }
    }
  }
}
```

```
POST /datetest/type/1
{
  "created_at":"2016-04-14T18:36:31+02:00"
}
```

```
GET /datetest/_search
{
  "fielddata_fields": ["created_at"]
}
```

Returns:

```
{
   "took": 106,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 1,
      "hits": [
         {
            "_index": "datetest",
            "_type": "type",
            "_id": "1",
            "_score": 1,
            "_source": {
               "created_at": "2016-04-14T18:36:31+02:00"
            },
            "fields": {
               "created_at": [
                  1460651791000
               ]
            }
         }
      ]
   }
}
```

And 1460651791000 = Thu, 14 Apr 2016 16:36:31 UTC = 2016-04-14T18:36:31+02:00

Can you send your `localhost:9200/_cluster/state?pretty` in a file?

For the shutdown problem, which version of Logstash are you using?

**Comment by tolecnal** [comment]
Please find the attached cluster.state file for the cluster status.

As for the version of Logstash, that's at 2.3.1 currently (running from the official repository).

Also, when tailing the logstash log file I see the following, which I think is quite vital to why this might be failing:
```
"status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"Field name [type.] cannot contain '.'"}}}, :level=>:warn}
```

If you require any more information, just shout out.

**Comment by ppf2** [comment]
This is a different issue:

```
"status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"Field name [type.] cannot contain '.'"}}}, :level=>:warn}
```

It looks like you may have custom fields in Zendesk that are named `type.` - which is not allowed in Elasticsearch.  If you have any fields with a dot in its name, you will have to run this through the [Logstash dedot filter](https://www.elastic.co/blog/introducing-the-de_dot-filter) before sending the events to the ES output plugin.

On the original issue:

```
Mapping conflict! 2 fields are defined as several types (string, integer, etc) across the indices that match this pattern. You may still be able to use these conflict fields in parts of Kibana, but they will be unavailable for functions that require Kibana to know their type. Correcting this issue will require reindexing your data.
```

This is because 3 of your indices (zd_comments, zd_users and zd_orgs) have the created_at/updated_at fields defined as strings. 

```
        "mappings" : {
          "user" : {
            "properties" : {
              "shared" : {
                "type" : "boolean"
              },
              "last_login_at" : {
                "type" : "string"
              },
              "notes" : {
                "type" : "string"
              },
              "role" : {
                "type" : "string"
              },
              "signature" : {
                "type" : "string"
              },
              "moderator" : {
                "type" : "boolean"
              },
              "shared_agent" : {
                "type" : "boolean"
              },
              "created_at" : {
                "type" : "string"  <----------
              },
```

From the Zendesk Users API, the created_at is in the format that conforms to the format used in the example ES index templates:

```
    {
      "alias": "",
      "created_at": "2014-07-08T19:58:07Z",
      "id": 323349418,
      "locale": "en-US",
      "suspended": false,
      "url": "https://domain.zendesk.com/api/v2/users/323349418.json",
```

So the fact that these indices have created_at/updated_at fields created as strings means that these indices were created at the time when you have not yet created the index templates for them in Elasticsearch, or that the template created in Elasticsearch is not actually being applied to the indices created.  

From looking at your templates defined and the resulting index names, the issue appears to be in your Logstash configuration.  The 3 templates have the template matching criteria defined as zd_organization, zd_user and zd_comment, but your indices are created with names zd_orgs, zd_users and zd_comments - which do not match the index names expected by the templates, which means that these indices will not be using any templates and will default to strings for fields like created_at/updated_at.   You will have to ensure that your Logstash indices are created with index names that are expected by the templates.

Will have to look into the shutdown issue.

**Comment by ppf2** [comment]
Type and data parsing issues here are not likely plugin issues.  Logstash have made various improvements in shutdown mechanism in 2.x and further improvements in 5.x with additional forced [shutdown](https://www.elastic.co/guide/en/logstash/current/shutdown.html) flags available.
